# Makefile.Vx
TOP = ../../..
include $(TOP)/config/CONFIG_APP
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

SRCS.c += ../scalerRecord.c ../devScaler.c

LIBNAME = baseLib

STD_BIN = .
include ../stdLIBOBJS		#defines STDLIBOBJS
PROD += stdLib

INSTALLS += iocCore seq
PROD += $(STDLIBOBJS)

include $(TOP)/config/RULES.Vx
#----------------------------------------
#  ADD RULES AFTER THIS LINE

stdLib: $(STDLIBOBJS)
	$(LINK.c) $@ $(STDLIBOBJS)
